Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,8 +1,11 @@
 name: test
+
 on: [push, workflow_dispatch]
+
 jobs:
   test:
     runs-on: ubuntu-24.04
+
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
@@ -10,26 +13,34 @@ jobs:
           submodules: recursive
 
       - name: Install iverilog
-        shell: bash
-        run: sudo apt-get update && sudo apt-get install -y iverilog
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y iverilog
 
-      # Set Python up and install cocotb
-      - name: Setup python
+      - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.11'
 
       - name: Install Python packages
-        shell: bash
         run: pip install -r test/requirements.txt
 
       - name: Run tests
+        working-directory: test
         run: |
-          cd test
-          make clean
-          make
-          # make will return success even if the test fails, so check for failure in the results.xml
-          ! grep failure results.xml
+          make clean || true
+          make || { echo "Make failed"; exit 1; }
+
+      - name: Check for test failures
+        if: always()
+        working-directory: test
+        run: |
+          if grep -q failure results.xml; then
+            echo "Test failed"
+            exit 1
+          else
+            echo "Test passed"
+          fi
 
       - name: Test Summary
         uses: test-summary/action@v2.3
@@ -37,7 +48,7 @@ jobs:
           paths: "test/results.xml"
         if: always()
 
-      - name: upload vcd
+      - name: Upload VCD and XML artifacts
         if: success() || failure()
         uses: actions/upload-artifact@v4
         with:
