Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,33 +1,47 @@
-name: Verilog Testbench
-
-on: [push, pull_request]
-
+name: test
+on: [push, workflow_dispatch]
 jobs:
-  run-testbench:
-    runs-on: ubuntu-latest
-
+  test:
+    runs-on: ubuntu-24.04
     steps:
-      - name: Checkout repository
+      - name: Checkout repo
         uses: actions/checkout@v4
-
-      - name: Install Icarus Verilog
-        run: sudo apt-get install -y iverilog
-
-      - name: Compile Verilog files
-        run: |
-          iverilog -o sim.vvp src/project.v test/tb.v
-
-      - name: Run simulation
-        run: |
-          vvp sim.vvp
-
-      - name: Create dummy results.xml (to prevent ENOENT error)
-        run: |
-          mkdir -p test
-          echo "<testsuite><testcase classname='dummy' name='sim-test'/></testsuite>" > test/results.xml
-
-      - name: Upload test results
-        uses: actions/upload-artifact@v3
         with:
-          name: test-report
-          path: test/results.xml
+          submodules: recursive
+
+      - name: Install iverilog
+        shell: bash
+        run: sudo apt-get update && sudo apt-get install -y iverilog
+
+      # Set Python up and install cocotb
+      - name: Setup python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+
+      - name: Install Python packages
+        shell: bash
+        run: pip install -r test/requirements.txt
+
+      - name: Run tests
+        run: |
+          cd test
+          make clean
+          make
+          # make will return success even if the test fails, so check for failure in the results.xml
+          ! grep failure results.xml
+
+      - name: Test Summary
+        uses: test-summary/action@v2.3
+        with:
+          paths: "test/results.xml"
+        if: always()
+
+      - name: upload vcd
+        if: success() || failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-vcd
+          path: |
+            test/tb.vcd
+            test/results.xml
